In [1]:
import pandas as pd
import numpy as np
import glob

SOURCE = r'../source/'

In [9]:
files = glob.glob(pathname= SOURCE + '*.csv')
dfs = {f.split('_')[-1].replace('.csv', ''): pd.read_csv(f) for f in files}

In [10]:
dfs.keys()

dict_keys(['agency', 'tabelaVeiculo', 'linhas', 'trechosItinerarios', 'tabelaLinha', 'shapeLinha', 'pontosLinha', 'pois'])

In [11]:
tabelaVeiculo = dfs['tabelaVeiculo']
pois = dfs['pois']
agency = dfs['agency']
tabelaLinha = dfs['tabelaLinha']
pontosLinha = dfs['pontosLinha']
trechosItinerarios = dfs['trechosItinerarios']
linhas = dfs['linhas']
shapeLinha = dfs['shapeLinha']

In [12]:
urbs = agency[agency['agency_name']=='Urbanização de Curitiba S/A']
urbs_id = urbs['agency_id'][0].astype('int16')

## agency.txt

In [13]:
agency.head(5)

,agency_id,agency_name,agency_url,agency_timezone,agency_lang
0,1,Urbanização de Curitiba S/A,https://www.urbs.curitiba.pr.gov.br/,America/Sao_Paulo,pt-BR

---

## routes.txt (linhas)

In [14]:
linhas['agency_id']= urbs_id
linhas['route_type'] = np.int16(3)

linhas = linhas.rename(columns={
   'COD':'route_id',
   'NOME':'route_long_name', 
   'NOME_COR':'route_color_name',
   'SOMENTE_CARTAO':'only_card',
   'CATEGORIA_SERVICO':'service_category',
})

linhas = linhas[['route_id', 'agency_id',
                 'route_long_name', 'route_type', 
                 'only_card', 'service_category',
                 'route_color_name']]

linhas.head(5)

,route_id,agency_id,route_long_name,route_type,only_card,service_category,route_color_name
0,464,1,A. MUNHOZ / JD. BOTÂNICO,3,S,CONVENCIONAL,AMARELA
1,226,1,ABAETÉ,3,S,ALIMENTADOR,LARANJA
2,182,1,ABRANCHES,3,S,TRONCAL,AMARELA
3,332,1,ACRÓPOLE,3,S,ALIMENTADOR,LARANJA
4,334,1,AGRÍCOLA,3,S,ALIMENTADOR,LARANJA

---

## pois.txt (extra file besides the required ones)

In [15]:
if 'POI_DESC' in pois.columns.values:
    pois = pois.drop(['POI_DESC'], axis=1)

pois = pois.rename(columns={
    'POI_NAME': 'poi_name',
    'POI_CATEGORY_NAME': 'poi_category',
    'POI_LAT': 'poi_lat',
    'POI_LON': 'poi_lon'
})

pois.head(5)

                    poi_name  poi_category           poi_lat           poi_lon
0          Adm. Regional CIC  ADM REGIONAL  -25,514461917365  -49,319652673957
1       Adm. Regional Cajuru  ADM REGIONAL  -25,455194588156  -49,217843315763
2  Adm. Regional Bairro Novo  ADM REGIONAL  -25,545293172409  -49,265672656927
3    Adm. Regional Boa Vista  ADM REGIONAL  -25,385362167558  -49,232463472866
4    Adm. Regional Boqueirão  ADM REGIONAL  -25,500873488704  -49,238528255855

---

## stops.txt (pontosLinha)

In [16]:
pontosLinha = pontosLinha.rename(columns={
    'NOME':'stop_name',
    'LAT':'stop_lat',
    'LON':'stop_lon',
    'NUM':'stop_id',
    'TIPO':'stop_desc',
    'SEQ':'seq',
    'GRUPO':'grupo',
    'SENTIDO':'sentido',
    'ITINERARY_ID': 'itinerary_id',
    'COD':'route_id'
})

pontosLinha.head(5)

,stop_name,stop_id,stop_lat,stop_lon,seq,grupo,sentido,stop_desc,itinerary_id,route_id
0,"Rua Rockefeller, 290 - Rebouças",140213,"-25,440709570169","-49,264190064557",11,NaN,Bom Retiro,Chapéu chinês,15914,175
1,"Av. Iguaçu, 462 - Rebouças",110052,"-25,440982096737","-49,266481978174",35,NaN,Sentido Pilarzinho,Novo mobiliário,10994,188
2,"R. dos Ferroviários, 926 - Cajuru",140240,"-25,45001456975","-49,206222915344",30,NaN,Terminal Capão Raso,Novo mobiliário,15555,030
3,"R. dos Ferroviários, 707 - Cajuru",140242,"-25,450825545448","-49,208406472387",49,NaN,Terminal Santa Cândida,Novo mobiliário,15573,030
4,"R. Nilo Peçanha,162 - Bom Retiro",110008,"-25,418907138692","-49,274696505794",18,NaN,Nestor de Castro,Novo mobiliário,8654,171

---
## trips.txt

In [17]:
shapeLinha.head()

    SHP                  LAT                 LON  COD
0  2612   -25,51231568263223  -49,29564508098565  602
1  2612   -25,51259077193037  -49,29563592791851  602
2  2612  -25,512727106234163  -49,29563168666107  602
3  2612  -25,512859204361412  -49,29562744540368  602
4  2612  -25,513149725321043   -49,2956182923366  602

In [18]:
dfs.keys()

dict_keys(['agency', 'tabelaVeiculo', 'linhas', 'trechosItinerarios', 'tabelaLinha', 'shapeLinha', 'pontosLinha', 'pois'])

In [19]:
tabelaLinha.head()

    HORA                    PONTO  DIA     NUM TABELA     ADAPT  COD
0  06:00    BAIRRO SANTA EFIGENIA    1  120422      1  ELEVADOR  260
1  06:30  AV.MAL.FLORIANO PEIXOTO    1  103271      1  ELEVADOR  260
2  07:00    BAIRRO SANTA EFIGENIA    1  120422      1  ELEVADOR  260
3  07:35  AV.MAL.FLORIANO PEIXOTO    1  103271      1  ELEVADOR  260
4  08:05    BAIRRO SANTA EFIGENIA    1  120422      1  ELEVADOR  260